site_name: data_server_stm32

markdown_extensions:
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml

nav:
  - Make Data Server - Part 2: 'doc_data_server.md'
  - Calculate LaCrosse TX141TH Checksum: 'doc_lacrosse.md'
