site_name: data_server_stm32

markdown_extensions:
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml

nav:
  - Data Server on STM32: 'doc_data_server.md'
  - LaCrosse TX141TH Checksum: 'doc_lacrosse.md'
